WINDOW_HEIGHT = 58
WINDOW_LENGTH = 238

WINDOW_DOWN = 65
WINDOW_UP   = 0

HOME_MENU_BUTTON_WIDTH = 40
HOME_MENU_BUTTON_HEIGHT = 25

LAST_SCORE = "LAST SCORE : "
SCORE = "SCORE : "

P1 = "AN AMAZING GAME FOR A CRAZY WORLD !"
HELP ="MOVE THE GAME BOARD TO THE LEFT TO START THE GAME "
HELP2="MOVE THE GAME BOARD TO THE RIGHT TO QUIT THE GAME "