WINDOW_HEIGHT = 58
WINDOW_LENGTH = 238

LAST_SCORE = "LAST SCORE : "
SCORE = "SCORE : "

HELP ="MOVE THE GAME BOARD TO THE LEFT TO START THE GAME \n\
MOVE THE GAME BOARD TO THE RIGHT TO QUIT THE GAME"

SEE_YOU_SOON = "THANKS, SEE YOU SOON !"
RETRY = "DON'T WORRY IT'S NORMAL ! TRY AGAIN !"

PLAYER_CHOOSE = "YOU CHOOSE THE "